name: safa_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  flutter_bloc: ^9.0.0
  go_router: ^14.2.1
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/i18n/
     

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo_safa_app3.png"
  min_sdk_android: 21
